{% set name = "eoreader" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: 79bc712f1ca3c1f58a417b758c4fe664e444c34420edafcd2bf6c6b0c79b0a6e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geopandas >=0.11.0
    - lxml
    - h5netcdf
    - python >=3.8
    - rasterio >=1.3.0
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - rtree
    - cloudpathlib >=0.9.0
    - sertit >=1.20.3
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.2.0
    - pyresample
    - zarr
    - dicttoxml

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.stac
    - eoreader.products
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
