{% set name = "eoreader" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: 89b035f35c03f21a69bd345fc2ed9a62705eb221475dc8e636e51f17568bc530

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geopandas >=0.9.0
    - lxml
    - netcdf4
    - python >=3.7
    - rasterio >=1.2.2
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - rtree
    - cloudpathlib
    - sertit >=1.7.3
    - validators

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.products.optical
    - eoreader.products.sar
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
