{% set name = "eoreader" %}
{% set version = "0.20.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: a01f7e002b1a6775b5c1ba2bd2f46bf7ee755098994d5e2fa2823e2d91261244

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - geopandas >=0.11.0
    - lxml
    - h5netcdf
    - python >=3.9
    - rasterio >=1.3.0
    - xarray >=0.18.0
    - rioxarray >=0.10.0
    - rtree
    - cloudpathlib >=0.10.0
    - sertit >=1.27.3
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.3.0
    - pyresample
    - zarr
    - dicttoxml

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.stac
    - eoreader.products
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
