{% set name = "eoreader" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: efa4a081590751c2b3acbbfeba4038a753b99ddb5b95bf448c4b2ee5f52e66fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  always_include_files:
    - eoreader/data/cplx_s1_preprocess_default.xml
    - eoreader/data/cplx_sar_preprocess_default.xml
    - eoreader/data/grd_s1_preprocess_default.xml
    - eoreader/data/grd_sar_preprocess_default.xml
    - eoreader/data/grd_sar_preprocess_fallback.xml
    - eoreader/data/sar_despeckle_default.xml

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geopandas >=0.9.0
    - lxml
    - h5netcdf
    - python >=3.7
    - rasterio >=1.2.2
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - rtree
    - cloudpathlib
    - sertit >=1.11.0
    - validators

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.products.optical
    - eoreader.products.sar
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
