{% set name = "eoreader" %}
{% set version = "0.21.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: 23937a01d809a364695ea141ef1272a478fac461e1ec64619ab02fbbb311839f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.9
  run:
    - geopandas >=0.14.4
    - lxml
    - h5netcdf
    - python >=3.9
    - rasterio >=1.3.10
    - xarray >=2024.06.0
    - rioxarray >=0.10.0
    - odc-geo >=0.4.6
    - rtree
    - cloudpathlib >=0.12.1
    - sertit >=1.42.2
    - validators
    - matplotlib-base
    - methodtools
    - pystac
    - spyndex >=0.3.0
    - pyresample
    - zarr
    - dicttoxml

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.stac
    - eoreader.products
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
