{% set name = "eoreader" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eoreader-{{ version }}.tar.gz
  sha256: 966db740447c0c7aad9a1425f40d85169888fb43972acbe9af177cae61b8f2e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - geopandas >=0.9.0
    - lxml
    - h5netcdf
    - python >=3.7
    - rasterio >=1.2.2
    - xarray >=0.18.0
    - rioxarray >=0.4.0
    - rtree
    - cloudpathlib
    - sertit >=1.14.0
    - validators
    - matplotlib-base
    - methodtools

test:
  imports:
    - eoreader
    - eoreader.bands
    - eoreader.stac
    - eoreader.products
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/sertit/eoreader/
  summary: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  license: Apache-2.0
  license_file: LICENSE
  description: Remote-sensing opensource python library reading optical and SAR sensors, loading and stacking bands, clouds, DEM and index.
  doc_url: https://eoreader.readthedocs.io/en/latest/
  dev_url: http://github.com/sertit/eoreader

extra:
  recipe-maintainers:
    - remi-braun
